apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  profile: ambient
  tag: 1.21.0
  revision: 1-21
  components:
    ingressGateways:
      - name: istio-ingressgateway
        enabled: true
    base:
      enabled: true
    cni:
      enabled: true
    ztunnel:
      enabled: true
      # hub: gcr.io/istio-testing/build-tools
      # tag: master-8fb9ce88f6ad4cdd35c1660cd0ad0ab67eff4c6c
    pilot:
      k8s:
        env:
        - name: PILOT_SKIP_VALIDATE_TRUST_DOMAIN
          value: "true"
        - name: PILOT_ENABLE_K8S_SELECT_WORKLOAD_ENTRIES
          value: "false"
  values:
    global:
      meshID: mesh1
      multiCluster:
        clusterName: cluster1
      network: network1
      logging:
        level: "default:debug"
  meshConfig:
    accessLogFile: /dev/stdout
    accessLogFormat: |
       [%START_TIME%] "%REQ(:METHOD)% %REQ(X-ENVOY-ORIGINAL-PATH?:PATH)% %PROTOCOL%" %RESPONSE_CODE% flag: %RESPONSE_FLAGS% %RESPONSE_CODE_DETAILS% %CONNECTION_TERMINATION_DETAILS% "%UPSTREAM_TRANSPORT_FAILURE_REASON%" %BYTES_RECEIVED% %BYTES_SENT% %DURATION% %RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)% "%REQ(X-FORWARDED-FOR)%" "%REQ(USER-AGENT)%" "%REQ(X-REQUEST-ID)%" "%REQ(:AUTHORITY)%" "%UPSTREAM_HOST%" %UPSTREAM_CLUSTER% %UPSTREAM_LOCAL_ADDRESS% %DOWNSTREAM_LOCAL_ADDRESS% %DOWNSTREAM_REMOTE_ADDRESS% %REQUESTED_SERVER_NAME% %ROUTE_NAME% traceID=%REQ(x-b3-traceid)%
    defaultConfig:
      holdApplicationUntilProxyStarts: true
      proxyMetadata:
        ISTIO_META_DNS_CAPTURE: "true"
        ISTIO_META_DNS_AUTO_ALLOCATE: "false"
        DNS_PROXY_ADDR: "0.0.0.0:15053"
    outboundTrafficPolicy:
      mode: ALLOW_ANY